# <center>L2 Computational Physics</center>

## <center>Week 3: Differential Equations I</center>

In [1]:
# usual packages to import
import numpy 
import matplotlib.pyplot as plt
%matplotlib inline

In this notebook, you will generate and plot the decay curve for Iodine-133 analytically and numerically. $^{133}\textrm{I}$ has a half life $t_{1/2}$ of 20.8 hours. This means that half of the nuclei will have decayed after time $t_{1/2}$. Derive the mean lifetime $\tau$ from that information.

In [2]:
# define a function to calculate the mean lifetime from the half life
def meanLifetime(halfLife):
    value = halfLife/numpy.log(2)
    return value

T_HALF = 20.8
TAU = meanLifetime(T_HALF)


Check your average lifetime:

In [3]:
# this test is worth 1 mark
assert numpy.isclose(TAU, 30.0080568505)         

### The Decay Equation

Implement the function `f_rad` such that the differential equation 

$$ \frac{dN}{dt} = f_{rad}(N,t)$$

describes the radioactive decay process.

- *Your function should return values using hours as the time unit.*
- *The function should use the constant* `TAU`.

In [4]:
def f_rad(N, t):
    result = - (1/TAU) * N
    return result

Make sure your function works:

In [5]:
# this test cell is worth 1 mark
assert numpy.isclose(f_rad(1000, 0), -33.324383681)           

Solve this first order, ordinary differential equation analytically. Implement this function below, naming it `analytic`. The function should take an initial number of atoms `N0` at time `t=0`, and a time argument. The function should return nuclei count at the time argument. Make sure the function also works for numpy arrays.

In [6]:
def analytic(N0, t):
    result2 = N0 * numpy.e ** (-t/TAU)
    return result2

Check your answer for a single time:

In [7]:
# this test is worth 1 mark
assert numpy.isclose(analytic(1000, 41.6), 250.0)           

In [8]:
# this test is worth 1 mark
assert numpy.isclose(analytic(1000, numpy.arange(0, 60, 6)), 
                     [1000.        ,  818.77471839,  670.39203948,  548.90005334,
                       449.4254866 ,  367.97822623,  301.29126855,  246.68967356,
                       201.983268  ,  165.37879338]).all()


## Numerically Solving the ODE

We now wish to solve our differential equation numerically. We shall do this using Euler's and RK4 methods.

### Euler's Method

Create a function which takes as its arguments the initial number of atoms, `n0`, the initial time `t0`, the time step, `dt`, and the number of steps to perform, `n_steps`.  This function should return an array of the number of counts at each time step using Euler's method. This array should contain the initial and final values, so the array length should be `n_steps+1` 

In [43]:
def solve_euler(f, n0, t0, dt, n_panels):
    steps = n_panels + 1
    v = numpy.zeros((steps))
    v[0] = n0
    n = n0
    for i in range(1,steps):
       v[i] = n + dt * f(n ,t0  +(i-1)*dt) 
       n = v[i]
    return v
  
    

Try your solution:

In [44]:
# this test is worth 1 mark
assert len(solve_euler(f_rad, 1000, 0, 1, 17)) == 18

In [45]:
# this test is worth 2 marks
assert numpy.isclose(solve_euler(f_rad, 1000, 0, 6, 1), [1000.,  800.05369792]).all()

In [46]:
# this test is worth 2 mark
assert numpy.isclose(solve_euler(f_rad, 1000, 0, 6, 10), [1000.        ,  800.05369792,  640.08591955,  512.10310692,
                                                409.7099844 ,  327.7899881 ,  262.24959212,  209.81375595,
                                                167.86227132,  134.29883091,  107.4462763 ]).all()

### RK 4 method

Implement the RK4 method in the `solve_RK4` function. The arguments are the same as for `solve_euler`.

In [47]:
def solve_RK4(f, n0, t0, dt, nsteps):
    steps = nsteps + 1
    v = numpy.zeros((steps))
    v[0] = n0
    n = n0
    grad1 = f(n0,t0)
    grad2 = 0
    for i in range(1,steps):
       k1 = f(n,t0+(i-1)*dt/2)
       pointb = n + (dt/2) * (k1)
       k2 = f(pointb,t0+(i)*(dt/2))
       pointb2 = n + (dt/2) * k2
       k3 = f(pointb2,t0+(i)*dt/2)
       pointc = n + k3 * (dt)      
       k4 = f(pointc,t0+(i)*dt)
       k = (1/6)*(k1+2*k2+2*k3+k4)
       v[i] = n + k * dt
       n = v[i]
    return v
    

In [48]:
# This checks that we return an array of the right length
# this test is worth 1 mark
assert len(solve_RK4(f_rad, 1000, 0, 1, 17)) == 18

In [49]:
# This checks that a single step is working
# this test is worth 2 mark
assert numpy.isclose(solve_RK4(f_rad, 1000,0, 6, 1), [1000.,  818.7773]).all()

In [50]:
# This checks multiple steps
# this test is worth 2 marks
assert numpy.isclose(solve_RK4(f_rad, 1000, 0, 6, 10), [
    1000.,
    818.77729521,  
    670.39625915,  
    548.90523578,
    449.43114428,  
    367.9840167,  
    301.29695787,  
    246.69510822, 
    201.98835345,  
    165.3834777,  
    135.41223655]).all()

## Plotting task

**Task 1: **

Create a plot to show that the RK4 method has an error that scales better with the number of steps than the Euler method. (click on the "+" button to create new cells.)       [task worth 5 marks]


In [67]:
xs = numpy.linspace(1,100,1)
v = numpy.zeros(100, dtype=object)
for i in range(0,99):
  v[i] = solve_euler(f_rad, 1000, 0, 6, i)
print(v)
  




[array([1000.]) array([1000.        ,  800.05369792])
 array([1000.        ,  800.05369792,  640.08591955])
 array([1000.        ,  800.05369792,  640.08591955,  512.10310692])
 array([1000.        ,  800.05369792,  640.08591955,  512.10310692,
        409.7099844 ])
 array([1000.        ,  800.05369792,  640.08591955,  512.10310692,
        409.7099844 ,  327.7899881 ])
 array([1000.        ,  800.05369792,  640.08591955,  512.10310692,
        409.7099844 ,  327.7899881 ,  262.24959212])
 array([1000.        ,  800.05369792,  640.08591955,  512.10310692,
        409.7099844 ,  327.7899881 ,  262.24959212,  209.81375595])
 array([1000.        ,  800.05369792,  640.08591955,  512.10310692,
        409.7099844 ,  327.7899881 ,  262.24959212,  209.81375595,
        167.86227132])
 array([1000.        ,  800.05369792,  640.08591955,  512.10310692,
        409.7099844 ,  327.7899881 ,  262.24959212,  209.81375595,
        167.86227132,  134.29883091])
 array([1000.        ,  800.05369792, 